CREATE TABLE user_endereco(
	CEP VARCHAR(255) NOT NULL,
	Logradouro VARCHAR(255) NOT NULL,
	Numero VARCHAR(255) NOT NULL,
	Complemento VARCHAR(255),
	Bairro VARCHAR(255) NOT NULL,
	Cidade VARCHAR(255) NOT NULL,
	Estado VARCHAR(255) NOT NULL
);